#! /bin/bash

mkdir -p build

lllc --hex --optimise src/ETHSwap.lsp > build/ETHSwap.lll.bin && \
  solc --bin --abi -o build --overwrite src/ETHSwap.sol 2>/dev/null && mv build/ETHSwap.abi build/ETHSwap.json && \
  node index.js
